####################################################
# remember to add this file name in .gitignore file
####################################################

REDIS_HOST     = "host"
REDIS_PORT     = 11111
REDIS_PASSWORD = "password"

DB_FRAMEWORK = "redis"