####################################################
# remember to add this file name in .gitignore file
####################################################

REDIS_HOST     = "redis_streamlit_app"
REDIS_PORT     = 6379
REDIS_PASSWORD = "senha123"

DB_FRAMEWORK = "redis"