####################################################
# remember to add this file name in .gitignore file
####################################################

HOST     = "host"
PORT     = 11111
PASSWORD = "password"

DB_FRAMEWORK = "redis"